### ISSUE TITLE
[BUG] Syntax error, non ascii char

### ISSUE THREAD

**Issue by ulvida** [UdelaRInterior/zoom-recordings-downloader#4]
Running the tool on a fresh Debian 10.7 (proxmox container) I come to the following error: 
```
root@buenaso:/usr/sbin/zoom-recordings-downloader# python descargar_noreste.py 
Traceback (most recent call last):
  File "descargar_noreste.py", line 3, in <module>
    from zoom_recordings import download_recordings
  File "/usr/sbin/zoom-recordings-downloader/zoom_recordings.py", line 169
SyntaxError: Non-ASCII character '\xc3' in file /usr/sbin/zoom-recordings-downloader/zoom_recordings.py on line 169, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
an indeed [line 169](https://github.com/UdelaRInterior/zoom-recordings-downloader/blob/8405d74196e61003d181b43fe6dbbf1e752dbb1f/zoom_recordings.py#L169) deaqls with char encoding and has special character. And [the referenced doc](https://www.python.org/dev/peps/pep-0263/#defining-the-encoding) says that codification should be declared in the first or second line of the file (which is not) and that default codification is standard ascii. 

I'll try to add a char codification line to the library.

**Comment by ulvida** [comment]
Sorry, I was running the script with python (i.e., by default in debian buster, python 2.7) and not python3.

**Comment by ulvida** [comment]
Sorry, I was running the script with python (i.e., by default in debian buster, python 2.7) and not python3.
